#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=40
STOP=90


start() {
  wsroutingserver  2> /dev/null > /dev/null &
}

stop() {
  killall wsroutingserver
}

restart() {
  stop
  start
}

